name = "xigai-quiz"
pages_build_output_dir = "./public"
compatibility_date = "2026-05-31"

[[d1_databases]]
binding = "DB"
database_name = "xigai-db"
database_id = "00fbdc36-26ed-4658-8cea-1b5f094fa9f7"